//
//  Session+SampleData.swift
//  LetSwift
//
//  Created by 박진서 on 8/30/24.
//

import Foundation

extension Session {
    static let sampleData: [Session] = [
        Session(id: "1", name: "SwiftUI의 최신 기능", nameEn: "Latest Features in SwiftUI", type: "presentation", track: "Track A", trackEn: "Track A", venue: "메인 홀", venueEn: "Main Hall", speaker: Speaker.sampleData[0], startTime: Date().addingTimeInterval(0), duration: 3600, endTime: Date().addingTimeInterval(3600), keynoteUrl: "https://www.keynote1.com", videoUrl: "https://www.video1.com"),
        Session(id: "2", name: "Swift Concurrency 실전 적용", nameEn: "Practical Swift Concurrency", type: "workshop", track: "Track B", trackEn: "Track B", venue: "워크숍 룸", venueEn: "Workshop Room", speaker: Speaker.sampleData[1], startTime: Date().addingTimeInterval(3600), duration: 5400, endTime: Date().addingTimeInterval(9000), keynoteUrl: "https://www.keynote2.com", videoUrl: "https://www.video2.com"),
        Session(id: "3", name: "iOS 성능 최적화 전략", nameEn: "iOS Performance Optimization Strategies", type: "presentation", track: "Track A", trackEn: "Track A", venue: "메인 홀", venueEn: "Main Hall", speaker: Speaker.sampleData[2], startTime: Date().addingTimeInterval(9000), duration: 3600, endTime: Date().addingTimeInterval(12600), keynoteUrl: "https://www.keynote3.com", videoUrl: "https://www.video3.com"),
        Session(id: "4", name: "Swift Package Manager 심화", nameEn: "Advanced Swift Package Manager", type: "workshop", track: "Track B", trackEn: "Track B", venue: "워크숍 룸", venueEn: "Workshop Room", speaker: Speaker.sampleData[3], startTime: Date().addingTimeInterval(12600), duration: 5400, endTime: Date().addingTimeInterval(18000), keynoteUrl: "https://www.keynote4.com", videoUrl: "https://www.video4.com"),
        Session(id: "5", name: "SwiftUI와 UIKit 통합하기", nameEn: "Integrating SwiftUI with UIKit", type: "presentation", track: "Track A", trackEn: "Track A", venue: "메인 홀", venueEn: "Main Hall", speaker: Speaker.sampleData[4], startTime: Date().addingTimeInterval(18000), duration: 3600, endTime: Date().addingTimeInterval(21600), keynoteUrl: "https://www.keynote5.com", videoUrl: "https://www.video5.com"),
        Session(id: "6", name: "Core ML을 이용한 iOS 앱 개발", nameEn: "iOS App Development with Core ML", type: "workshop", track: "Track B", trackEn: "Track B", venue: "워크숍 룸", venueEn: "Workshop Room", speaker: Speaker.sampleData[5], startTime: Date().addingTimeInterval(21600), duration: 5400, endTime: Date().addingTimeInterval(27000), keynoteUrl: "https://www.keynote6.com", videoUrl: "https://www.video6.com"),
        Session(id: "7", name: "Swift 디자인 패턴", nameEn: "Swift Design Patterns", type: "presentation", track: "Track A", trackEn: "Track A", venue: "메인 홀", venueEn: "Main Hall", speaker: Speaker.sampleData[6], startTime: Date().addingTimeInterval(27000), duration: 3600, endTime: Date().addingTimeInterval(30600), keynoteUrl: "https://www.keynote7.com", videoUrl: "https://www.video7.com"),
        Session(id: "8", name: "iOS 테스팅 전략", nameEn: "iOS Testing Strategies", type: "workshop", track: "Track B", trackEn: "Track B", venue: "워크숍 룸", venueEn: "Workshop Room", speaker: Speaker.sampleData[7], startTime: Date().addingTimeInterval(30600), duration: 5400, endTime: Date().addingTimeInterval(36000), keynoteUrl: "https://www.keynote8.com", videoUrl: "https://www.video8.com"),
        Session(id: "9", name: "Swift와 서버 사이드 개발", nameEn: "Server-Side Development with Swift", type: "presentation", track: "Track A", trackEn: "Track A", venue: "메인 홀", venueEn: "Main Hall", speaker: Speaker.sampleData[8], startTime: Date().addingTimeInterval(36000), duration: 3600, endTime: Date().addingTimeInterval(39600), keynoteUrl: "https://www.keynote9.com", videoUrl: "https://www.video9.com"),
        Session(id: "10", name: "iOS 앱 보안", nameEn: "iOS App Security", type: "workshop", track: "Track B", trackEn: "Track B", venue: "워크숍 룸", venueEn: "Workshop Room", speaker: Speaker.sampleData[9], startTime: Date().addingTimeInterval(39600), duration: 5400, endTime: Date().addingTimeInterval(45000), keynoteUrl: "https://www.keynote10.com", videoUrl: "https://www.video10.com"),
        Session(id: "11", name: "SwiftUI 애니메이션 마스터하기", nameEn: "Mastering SwiftUI Animations", type: "presentation", track: "Track A", trackEn: "Track A", venue: "메인 홀", venueEn: "Main Hall", speaker: Speaker.sampleData[10], startTime: Date().addingTimeInterval(45000), duration: 3600, endTime: Date().addingTimeInterval(48600), keynoteUrl: "https://www.keynote11.com", videoUrl: "https://www.video11.com"),
        Session(id: "12", name: "iOS 앱 국제화 및 현지화", nameEn: "iOS App Internationalization and Localization", type: "workshop", track: "Track B", trackEn: "Track B", venue: "워크숍 룸", venueEn: "Workshop Room", speaker: Speaker.sampleData[11], startTime: Date().addingTimeInterval(48600), duration: 5400, endTime: Date().addingTimeInterval(54000), keynoteUrl: "https://www.keynote12.com", videoUrl: "https://www.video12.com"),
        Session(id: "13", name: "Swift 메모리 관리", nameEn: "Swift Memory Management", type: "presentation", track: "Track A", trackEn: "Track A", venue: "메인 홀", venueEn: "Main Hall", speaker: Speaker.sampleData[12], startTime: Date().addingTimeInterval(54000), duration: 3600, endTime: Date().addingTimeInterval(57600), keynoteUrl: "https://www.keynote13.com", videoUrl: "https://www.video13.com"),
        Session(id: "14", name: "ARKit를 이용한 증강 현실 앱 개발", nameEn: "Augmented Reality App Development with ARKit", type: "workshop", track: "Track B", trackEn: "Track B", venue: "워크숍 룸", venueEn: "Workshop Room", speaker: Speaker.sampleData[13], startTime: Date().addingTimeInterval(57600), duration: 5400, endTime: Date().addingTimeInterval(63000), keynoteUrl: "https://www.keynote14.com", videoUrl: "https://www.video14.com"),
        Session(id: "15", name: "Swift 프로토콜 지향 프로그래밍", nameEn: "Protocol-Oriented Programming in Swift", type: "presentation", track: "Track A", trackEn: "Track A", venue: "메인 홀", venueEn: "Main Hall", speaker: Speaker.sampleData[14], startTime: Date().addingTimeInterval(63000), duration: 3600, endTime: Date().addingTimeInterval(66600), keynoteUrl: "https://www.keynote15.com", videoUrl: "https://www.video15.com"),
        Session(id: "16", name: "iOS 앱 출시 전략", nameEn: "iOS App Launch Strategies", type: "workshop", track: "Track B", trackEn: "Track B", venue: "워크숍 룸", venueEn: "Workshop Room", speaker: Speaker.sampleData[15], startTime: Date().addingTimeInterval(66600), duration: 5400, endTime: Date().addingTimeInterval(72000), keynoteUrl: "https://www.keynote16.com", videoUrl: "https://www.video16.com"),
        Session(id: "17", name: "Swift 함수형 프로그래밍", nameEn: "Functional Programming in Swift", type: "presentation", track: "Track A", trackEn: "Track A", venue: "메인 홀", venueEn: "Main Hall", speaker: Speaker.sampleData[16], startTime: Date().addingTimeInterval(72000), duration: 3600, endTime: Date().addingTimeInterval(75600), keynoteUrl: "https://www.keynote17.com", videoUrl: "https://www.video17.com"),
        Session(id: "18", name: "iOS 앱 접근성 향상", nameEn: "Improving iOS App Accessibility", type: "workshop", track: "Track B", trackEn: "Track B", venue: "워크숍 룸", venueEn: "Workshop Room", speaker: Speaker.sampleData[17], startTime: Date().addingTimeInterval(75600), duration: 5400, endTime: Date().addingTimeInterval(81000), keynoteUrl: "https://www.keynote18.com", videoUrl: "https://www.video18.com"),
         Session(id: "19", name: "Swift 메타프로그래밍", nameEn: "Metaprogramming in Swift", type: "presentation", track: "Track A", trackEn: "Track A", venue: "메인 홀", venueEn: "Main Hall", speaker: Speaker.sampleData[13], startTime: Date().addingTimeInterval(81000), duration: 3600, endTime: Date().addingTimeInterval(84600), keynoteUrl: "https://www.keynote19.com", videoUrl: "https://www.video19.com"),
        Session(id: "20", name: "iOS 앱 아키텍처 패턴", nameEn: "iOS App Architecture Patterns", type: "workshop", track: "Track B", trackEn: "Track B", venue: "워크숍 룸", venueEn: "Workshop Room", speaker: Speaker.sampleData[10], startTime: Date().addingTimeInterval(84600), duration: 5400, endTime: Date().addingTimeInterval(90000), keynoteUrl: "https://www.keynote20.com", videoUrl: "https://www.video20.com"),
    ]
}


extension Session.Speaker {
    static let sampleData: [Session.Speaker] = [
        Session.Speaker(id: "1", name: "김서연", nameEn: "Seoyeon Kim", imageName: "speaker1.png", imageUrl: "https://via.placeholder.com/150", description: "SwiftUI 전문가", social: Session.SocialMedia(web: "https://www.seoyeonkim.com", email: "seoyeon@example.com", github: "https://github.com/seoyeonkim", linkedin: "https://linkedin.com/seoyeonkim", x: "https://x.com/seoyeonkim", mastodon: "https://mastodon.social/@seoyeonkim", facebook: "https://facebook.com/seoyeonkim", instagram: "https://instagram.com/seoyeonkim", thread: "", youtube: "https://youtube.com/seoyeonkim")),
        Session.Speaker(id: "2", name: "이준호", nameEn: "Junho Lee", imageName: "speaker2.png", imageUrl: "https://via.placeholder.com/150", description: "iOS 성능 최적화 전문가", social: Session.SocialMedia(web: "https://www.junholee.com", email: "junho@example.com", github: "https://github.com/junholee", linkedin: "https://linkedin.com/junholee", x: "https://x.com/junholee", mastodon: "https://mastodon.social/@junholee", facebook: "https://facebook.com/junholee", instagram: "https://instagram.com/junholee", thread: "", youtube: "https://youtube.com/junholee")),
        Session.Speaker(id: "3", name: "박민지", nameEn: "Minji Park", imageName: "speaker3.png", imageUrl: "https://via.placeholder.com/150", description: "Swift 컴파일러 전문가", social: Session.SocialMedia(web: "https://www.minjipark.com", email: "minji@example.com", github: "https://github.com/minjipark", linkedin: "https://linkedin.com/minjipark", x: "https://x.com/minjipark", mastodon: "https://mastodon.social/@minjipark", facebook: "https://facebook.com/minjipark", instagram: "https://instagram.com/minjipark", thread: "", youtube: "https://youtube.com/minjipark")),
        Session.Speaker(id: "4", name: "최동훈", nameEn: "Donghoon Choi", imageName: "speaker4.png", imageUrl: "https://via.placeholder.com/150", description: "iOS 보안 전문가", social: Session.SocialMedia(web: "https://www.donghoonchoi.com", email: "donghoon@example.com", github: "https://github.com/donghoonchoi", linkedin: "https://linkedin.com/donghoonchoi", x: "https://x.com/donghoonchoi", mastodon: "https://mastodon.social/@donghoonchoi", facebook: "https://facebook.com/donghoonchoi", instagram: "https://instagram.com/donghoonchoi", thread: "", youtube: "https://youtube.com/donghoonchoi")),
        Session.Speaker(id: "5", name: "정유진", nameEn: "Yujin Jung", imageName: "speaker5.png", imageUrl: "https://via.placeholder.com/150", description: "SwiftUI 애니메이션 전문가", social: Session.SocialMedia(web: "https://www.yujinjung.com", email: "yujin@example.com", github: "https://github.com/yujinjung", linkedin: "https://linkedin.com/yujinjung", x: "https://x.com/yujinjung", mastodon: "https://mastodon.social/@yujinjung", facebook: "https://facebook.com/yujinjung", instagram: "https://instagram.com/yujinjung", thread: "", youtube: "https://youtube.com/yujinjung")),
        Session.Speaker(id: "6", name: "강현우", nameEn: "Hyeonwoo Kang", imageName: "speaker6.png", imageUrl: "https://via.placeholder.com/150", description: "iOS 네트워킹 전문가", social: Session.SocialMedia(web: "https://www.hyeonwookang.com", email: "hyeonwoo@example.com", github: "https://github.com/hyeonwookang", linkedin: "https://linkedin.com/hyeonwookang", x: "https://x.com/hyeonwookang", mastodon: "https://mastodon.social/@hyeonwookang", facebook: "https://facebook.com/hyeonwookang", instagram: "https://instagram.com/hyeonwookang", thread: "", youtube: "https://youtube.com/hyeonwookang")),
        Session.Speaker(id: "7", name: "송아영", nameEn: "Ayoung Song", imageName: "speaker7.png", imageUrl: "https://via.placeholder.com/150", description: "Swift 동시성 프로그래밍 전문가", social: Session.SocialMedia(web: "https://www.ayoungsong.com", email: "ayoung@example.com", github: "https://github.com/ayoungsong", linkedin: "https://linkedin.com/ayoungsong", x: "https://x.com/ayoungsong", mastodon: "https://mastodon.social/@ayoungsong", facebook: "https://facebook.com/ayoungsong", instagram: "https://instagram.com/ayoungsong", thread: "", youtube: "https://youtube.com/ayoungsong")),
        Session.Speaker(id: "8", name: "황재현", nameEn: "Jaehyun Hwang", imageName: "speaker8.png", imageUrl: "https://via.placeholder.com/150", description: "iOS 테스팅 전문가", social: Session.SocialMedia(web: "https://www.jaehyunhwang.com", email: "jaehyun@example.com", github: "https://github.com/jaehyunhwang", linkedin: "https://linkedin.com/jaehyunhwang", x: "https://x.com/jaehyunhwang", mastodon: "https://mastodon.social/@jaehyunhwang", facebook: "https://facebook.com/jaehyunhwang", instagram: "https://instagram.com/jaehyunhwang", thread: "", youtube: "https://youtube.com/jaehyunhwang")),
        Session.Speaker(id: "9", name: "임수진", nameEn: "Sujin Lim", imageName: "speaker9.png", imageUrl: "https://via.placeholder.com/150", description: "iOS 앱 아키텍처 전문가", social: Session.SocialMedia(web: "https://www.sujinlim.com", email: "sujin@example.com", github: "https://github.com/sujinlim", linkedin: "https://linkedin.com/sujinlim", x: "https://x.com/sujinlim", mastodon: "https://mastodon.social/@sujinlim", facebook: "https://facebook.com/sujinlim", instagram: "https://instagram.com/sujinlim", thread: "", youtube: "https://youtube.com/sujinlim")),
        Session.Speaker(id: "10", name: "오태훈", nameEn: "Taehoon Oh", imageName: "speaker10.png", imageUrl: "https://via.placeholder.com/150", description: "Core ML 전문가", social: Session.SocialMedia(web: "https://www.taehoonoh.com", email: "taehoon@example.com", github: "https://github.com/taehoonoh", linkedin: "https://linkedin.com/taehoonoh", x: "https://x.com/taehoonoh", mastodon: "https://mastodon.social/@taehoonoh", facebook: "https://facebook.com/taehoonoh", instagram: "https://instagram.com/taehoonoh", thread: "", youtube: "https://youtube.com/taehoonoh")),
        Session.Speaker(id: "11", name: "유하은", nameEn: "Haeun Yoo", imageName: "speaker11.png", imageUrl: "https://via.placeholder.com/150", description: "iOS 접근성 전문가", social: Session.SocialMedia(web: "https://www.haeunyoo.com", email: "haeun@example.com", github: "https://github.com/haeunyoo", linkedin: "https://linkedin.com/haeunyoo", x: "https://x.com/haeunyoo", mastodon: "https://mastodon.social/@haeunyoo", facebook: "https://facebook.com/haeunyoo", instagram: "https://instagram.com/haeunyoo", thread: "", youtube: "https://youtube.com/haeunyoo")),
        Session.Speaker(id: "12", name: "신동민", nameEn: "Dongmin Shin", imageName: "speaker12.png", imageUrl: "https://via.placeholder.com/150", description: "ARKit 전문가", social: Session.SocialMedia(web: "https://www.dongminshin.com", email: "dongmin@example.com", github: "https://github.com/dongminshin", linkedin: "https://linkedin.com/dongminshin", x: "https://x.com/dongminshin", mastodon: "https://mastodon.social/@dongminshin", facebook: "https://facebook.com/dongminshin", instagram: "https://instagram.com/dongminshin", thread: "", youtube: "https://youtube.com/dongminshin")),
        Session.Speaker(id: "13", name: "한지원", nameEn: "Jiwon Han", imageName: "speaker13.png", imageUrl: "https://via.placeholder.com/150", description: "Swift 서버 사이드 개발 전문가", social: Session.SocialMedia(web: "https://www.jiwonhan.com", email: "jiwon@example.com", github: "https://github.com/jiwonhan", linkedin: "https://linkedin.com/jiwonhan", x: "https://x.com/jiwonhan", mastodon: "https://mastodon.social/@jiwonhan", facebook: "https://facebook.com/jiwonhan", instagram: "https://instagram.com/jiwonhan", thread: "", youtube: "https://youtube.com/jiwonhan")),
        Session.Speaker(id: "14", name: "문승현", nameEn: "Seunghyun Moon", imageName: "speaker14.png", imageUrl: "https://via.placeholder.com/150", description: "iOS 앱 배포 및 CI/CD 전문가", social: Session.SocialMedia(web: "https://www.seunghyunmoon.com", email: "seunghyun@example.com", github: "https://github.com/seunghyunmoon", linkedin: "https://linkedin.com/seunghyunmoon", x: "https://x.com/seunghyunmoon", mastodon: "https://mastodon.social/@seunghyunmoon", facebook: "https://facebook.com/seunghyunmoon", instagram: "https://instagram.com/seunghyunmoon", thread: "", youtube: "https://youtube.com/seunghyunmoon")),
        Session.Speaker(id: "15", name: "조윤서", nameEn: "Yunseo Cho", imageName: "speaker15.png", imageUrl: "https://via.placeholder.com/150", description: "Swift 메모리 관리 전문가", social: Session.SocialMedia(web: "https://www.yunseocho.com", email: "yunseo@example.com", github: "https://github.com/yunseocho", linkedin: "https://linkedin.com/yunseocho", x: "https://x.com/yunseocho", mastodon: "https://mastodon.social/@yunseocho", facebook: "https://facebook.com/yunseocho", instagram: "https://instagram.com/yunseocho", thread: "", youtube: "https://youtube.com/yunseocho")),
        Session.Speaker(id: "16", name: "권태영", nameEn: "Taeyoung Kwon", imageName: "speaker16.png", imageUrl: "https://via.placeholder.com/150", description: "iOS 앱 국제화 및 현지화 전문가", social: Session.SocialMedia(web: "https://www.taeyoungkwon.com", email: "taeyoung@example.com", github: "https://github.com/taeyoungkwon", linkedin: "https://linkedin.com/taeyoungkwon", x: "https://x.com/taeyoungkwon", mastodon: "https://mastodon.social/@taeyoungkwon", facebook: "https://facebook.com/taeyoungkwon", instagram: "https://instagram.com/taeyoungkwon", thread: "", youtube: "https://youtube.com/taeyoungkwon")),
        Session.Speaker(id: "17", name: "백서윤", nameEn: "Seoyun Baek", imageName: "speaker17.png", imageUrl: "https://via.placeholder.com/150", description: "Swift 프로토콜 지향 프로그래밍 전문가", social: Session.SocialMedia(web: "https://www.seoyunbaek.com", email: "seoyun@example.com", github: "https://github.com/seoyunbaek", linkedin: "https://linkedin.com/seoyunbaek", x: "https://x.com/seoyunbaek", mastodon: "https://mastodon.social/@seoyunbaek", facebook: "https://facebook.com/seoyunbaek", instagram: "https://instagram.com/seoyunbaek", thread: "", youtube: "https://youtube.com/seoyunbaek")),
        Session.Speaker(id: "18", name: "남기훈", nameEn: "Kihun Nam", imageName: "speaker18.png", imageUrl: "https://via.placeholder.com/150", description: "iOS 앱 UI/UX 디자인 전문가", social: Session.SocialMedia(web: "https://www.kihunnam.com", email: "kihun@example.com", github: "https://github.com/kihunnam", linkedin: "https://linkedin.com/kihunnam", x: "https://x.com/kihunnam", mastodon: "https://mastodon.social/@kihunnam", facebook: "https://facebook.com/kihunnam", instagram: "https://instagram.com/kihunnam", thread: "", youtube: "https://youtube.com/kihunnam"))
    ]
}
